---
title: "Entropy map"
author: "Stephen A Lauer"
date: "3/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = here::here())
knitr::opts_chunk$set(echo=T, message=F, warning=F, eval=T, fig.align='center', fig.pos='ht')
```

```{r library}
library(tidyverse)
library(doMC)
library(sf)
source("source/util.R")
```

```{r load}
bgd0 <- readRDS("data/BGD_adm0.rds") %>% 
    st_as_sf() %>%
    transform_to_btm()

bgd2 <- readRDS("data/BGD_adm2.rds") %>% 
    st_as_sf() %>%
    mutate(adm2name = NAME_2) %>%
    transform_to_btm()
my_grid <- readRDS("data/grid_with_covs.rds")
```


## Entropy

Edit around lines 69-70 below to change RR cutoffs.
This can take a while to run.

```{r make-map-data, cache=T, eval=F}
registerDoMC(detectCores()-2)

## remove all grid cells not within the boundaries of BGD
## (i.e. in India or the ocean)
bgd_grid <- my_grid %>% 
    st_intersection(bgd2)

## read in all of the map data and combine them
file_list <- list.files(path="data/boot-maps/", pattern="boot_map_*")

all_boots <- foreach(i=seq(length(file_list)),.combine=rbind) %dopar%{
    readRDS(paste0("data/boot-maps/",file_list[i])) %>%
        filter(grid_id %in% bgd_grid$grid_id) %>% 
        mutate(rep=i)
}

## recalculate the sample_rr for all cells
all_boots_rr <- all_boots %>%
    left_join(my_grid %>% 
                  as_tibble() %>% 
                  select(grid_id, pop) %>% 
                  distinct()) %>% 
    group_by(rep) %>% 
    mutate(sample_rr=sample_rate/weighted.mean(sample_rate, pop)) %>% 
    ungroup()

## summarize each grid cell by a bunch of metrics
map_dat <- all_boots_rr %>% 
    group_by(grid_id, pop) %>%
    summarise(rr_median=median(sample_rr),
              ## this is the part to edit for different entropy measures
              rr_gt2=mean(sample_rr>2),
              rr_lthalf=mean(sample_rr<0.5),
              rr_lb=quantile(sample_rr, probs=.025),
              rr_ub=quantile(sample_rr, probs=.975),
              inc_mean=mean(sample_rate),
              inc_median=median(sample_rate),
              inc_lb=quantile(sample_rate, probs=.025),
              inc_ub=quantile(sample_rate, probs=.975)) %>%
    mutate(rr_med_bound=ifelse(abs(log2(rr_median))>2,
                               2*log2(rr_median)/abs(log2(rr_median)),
                               log2(rr_median)),
           rr_lb_bound=ifelse(abs(log2(rr_lb))>2,
                              2*log2(rr_lb)/abs(log2(rr_lb)),
                              log2(rr_lb)),
           rr_ub_bound=ifelse(abs(log2(rr_ub))>2,
                              2*log2(rr_ub)/abs(log2(rr_ub)),
                              log2(rr_ub)),
           rr_int_log_diff=rr_ub_bound-rr_lb_bound,
           inc_interval_width=inc_ub-inc_lb,
           implied_inf=inc_median*pop) %>% 
    left_join(bgd_grid)

saveRDS(map_dat, "generated_data/grid-cell-data.rds")

rm(all_boots)
rm(all_boots_rr)
```

```{r map}
map_dat <- readRDS("generated_data/grid-cell-data.rds") %>%
    mutate(entropy2=ifelse(rr_gt2==1 | rr_gt2==0,
                          0,-rr_gt2*log2(rr_gt2)-(1-rr_gt2)*log2(1-rr_gt2)),
           entropy_half=ifelse(rr_lthalf==1 | rr_lthalf==0,0,
                               -rr_lthalf*log2(rr_lthalf)-(1-rr_lthalf)*log2(1-rr_lthalf))) %>% 
    st_as_sf()

g2 <- ggplot() +
    geom_sf(data = map_dat,
            aes(fill = entropy2), color=NA,lwd = 0) +
    geom_sf(data = bgd0, fill = NA, lwd = 0.5) +
    # geom_sf(data = sampling_locs, color = 'black', pch=3,size = 1.2) +
    scale_fill_gradient("Entropy (cutoff=2)",
                        high="red", low="white",
                        limits=c(0,1), breaks=seq(0,1,.25)) +
    coord_sf(datum = NA)  +
    labs(x = "") +
    labs(y = "") +
    theme_void() +
    theme(legend.position="bottom")

g2

ggsave("entropy2.pdf",g2,height=6,width=6)

g_half <- ggplot() +
    geom_sf(data = map_dat,
            aes(fill = entropy_half), color=NA,lwd = 0) +
    geom_sf(data = bgd0, fill = NA, lwd = 0.5) +
    # geom_sf(data = sampling_locs, color = 'black', pch=3,size = 1.2) +
    scale_fill_gradient("Entropy (cutoff=0.5)",
                        high="red", low="white",
                        limits=c(0,1), breaks=seq(0,1,.25)) +
    coord_sf(datum = NA)  +
    labs(x = "") +
    labs(y = "") +
    theme_void() +
    theme(legend.position="bottom")

g_half

ggsave("entropy_half.pdf",g_half,height=6,width=6)
```
